// Code generated by the Encore v1.54.0 client generator. DO NOT EDIT.

// Disable eslint, jshint, and jslint for this file.
/* eslint-disable */
/* jshint ignore:start */
/*jslint-disable*/

/**
 * BaseURL is the base URL for calling the Encore application's API.
 */
export type BaseURL = string

export const Local: BaseURL = "http://localhost:4000"

/**
 * Environment returns a BaseURL for calling the cloud environment with the given name.
 */
export function Environment(name: string): BaseURL {
    return `https://${name}-bawo-wwb2.encr.app`
}

/**
 * PreviewEnv returns a BaseURL for calling the preview environment with the given PR number.
 */
export function PreviewEnv(pr: number | string): BaseURL {
    return Environment(`pr${pr}`)
}

const BROWSER = typeof globalThis === "object" && ("window" in globalThis);

/**
 * Client is an API client for the bawo-wwb2 Encore application.
 */
export default class Client {
    public readonly content: content.ServiceClient
    public readonly dashboard: dashboard.ServiceClient
    public readonly enrollment: enrollment.ServiceClient
    public readonly language: language.ServiceClient
    public readonly lesson: lesson.ServiceClient
    public readonly streak: streak.ServiceClient
    public readonly tracker: tracker.ServiceClient
    public readonly user: user.ServiceClient
    private readonly options: ClientOptions
    private readonly target: string


    /**
     * Creates a Client for calling the public and authenticated APIs of your Encore application.
     *
     * @param target  The target which the client should be configured to use. See Local and Environment for options.
     * @param options Options for the client
     */
    constructor(target: BaseURL, options?: ClientOptions) {
        this.target = target
        this.options = options ?? {}
        const base = new BaseClient(this.target, this.options)
        this.content = new content.ServiceClient(base)
        this.dashboard = new dashboard.ServiceClient(base)
        this.enrollment = new enrollment.ServiceClient(base)
        this.language = new language.ServiceClient(base)
        this.lesson = new lesson.ServiceClient(base)
        this.streak = new streak.ServiceClient(base)
        this.tracker = new tracker.ServiceClient(base)
        this.user = new user.ServiceClient(base)
    }

    /**
     * Creates a new Encore client with the given client options set.
     *
     * @param options Client options to set. They are merged with existing options.
     **/
    public with(options: ClientOptions): Client {
        return new Client(this.target, {
            ...this.options,
            ...options,
        })
    }
}

/**
 * ClientOptions allows you to override any default behaviour within the generated Encore client.
 */
export interface ClientOptions {
    /**
     * By default the client will use the inbuilt fetch function for making the API requests.
     * however you can override it with your own implementation here if you want to run custom
     * code on each API request made or response received.
     */
    fetcher?: Fetcher

    /** Default RequestInit to be used for the client */
    requestInit?: Omit<RequestInit, "headers"> & { headers?: Record<string, string> }

    /**
     * Allows you to set the authentication data to be used for each
     * request either by passing in a static object or by passing in
     * a function which returns a new object for each request.
     */
    auth?: auth.AuthParams | AuthDataGenerator
}

export namespace auth {
    /**
     * AuthParams defines the authentication parameters from the request
     */
    export interface AuthParams {
        Authorization: string
    }
}

export namespace content {
    /**
     * AudioURLResponse contains a URL for audio playback.
     */
    export interface AudioURLResponse {
        url: string
        "expires_at": string
    }

    /**
     * AudioUploadRequest contains the audio file data.
     */
    export interface AudioUploadRequest {
        /**
         * Base64-decoded audio bytes
         */
        data: string

        /**
         * e.g., "audio/mpeg", "audio/wav"
         */
        "content_type": string
    }

    /**
     * AudioUploadResponse contains the result of an audio upload.
     */
    export interface AudioUploadResponse {
        "audio_key": string
    }

    /**
     * CreateLessonParams contains parameters for creating a lesson.
     */
    export interface CreateLessonParams {
        "unit_id": string
        title: string
        description: string
        "xp_reward": number
        "sort_order": number
    }

    /**
     * CreateQuestionParams contains parameters for creating a question.
     */
    export interface CreateQuestionParams {
        "lesson_id": string
        type: QuestionType
        "prompt_text": string
        "use_tts": boolean
        "correct_answer": string
        options: string[]
        hint: string
        "sort_order": number
    }

    /**
     * CreateUnitParams contains parameters for creating a unit.
     */
    export interface CreateUnitParams {
        "language_id": string
        title: string
        description: string
        "sort_order": number
    }

    /**
     * DeleteLessonResponse is returned after deleting a lesson.
     */
    export interface DeleteLessonResponse {
        success: boolean
    }

    /**
     * DeleteQuestionResponse is returned after deleting a question.
     */
    export interface DeleteQuestionResponse {
        success: boolean
    }

    /**
     * DeleteUnitResponse is returned after deleting a unit.
     */
    export interface DeleteUnitResponse {
        success: boolean
    }

    /**
     * Lesson represents a single learning session within a unit.
     */
    export interface Lesson {
        id: uuid.UUID
        "unit_id": uuid.UUID
        title: string
        description: string
        "xp_reward": number
        "sort_order": number
        "created_at": string
        "updated_at": string
    }

    /**
     * LessonResponse wraps a single lesson.
     */
    export interface LessonResponse {
        lesson: Lesson
    }

    /**
     * LessonsResponse wraps a list of lessons.
     */
    export interface LessonsResponse {
        lessons: Lesson[]
    }

    /**
     * Question represents a question within a lesson.
     */
    export interface Question {
        id: uuid.UUID
        "lesson_id": uuid.UUID
        type: QuestionType
        "prompt_text": string
        "prompt_audio_key": string
        "use_tts": boolean
        "correct_answer": string
        options: string[]
        hint: string
        "sort_order": number
        "created_at": string
        "updated_at": string
    }

    /**
     * QuestionResponse wraps a single question.
     */
    export interface QuestionResponse {
        question: Question
    }

    /**
     * QuestionType defines the type of question.
     */
    export type QuestionType = string

    /**
     * QuestionsResponse wraps a list of questions.
     */
    export interface QuestionsResponse {
        questions: Question[]
    }

    /**
     * Unit represents a group of lessons within a language.
     */
    export interface Unit {
        id: uuid.UUID
        "language_id": uuid.UUID
        title: string
        description: string
        "sort_order": number
        "created_at": string
        "updated_at": string
    }

    /**
     * UnitResponse wraps a single unit.
     */
    export interface UnitResponse {
        unit: Unit
    }

    /**
     * UnitsResponse wraps a list of units.
     */
    export interface UnitsResponse {
        units: Unit[]
    }

    /**
     * UpdateLessonParams contains parameters for updating a lesson.
     */
    export interface UpdateLessonParams {
        title: string
        description: string
        "xp_reward": number
        "sort_order": number
    }

    /**
     * UpdateQuestionParams contains parameters for updating a question.
     */
    export interface UpdateQuestionParams {
        type: QuestionType
        "prompt_text": string
        "use_tts": boolean
        "correct_answer": string
        options: string[]
        hint: string
        "sort_order": number
    }

    /**
     * UpdateUnitParams contains parameters for updating a unit.
     */
    export interface UpdateUnitParams {
        title: string
        description: string
        "sort_order": number
    }

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.CreateLessonAdmin = this.CreateLessonAdmin.bind(this)
            this.CreateQuestionAdmin = this.CreateQuestionAdmin.bind(this)
            this.CreateUnitAdmin = this.CreateUnitAdmin.bind(this)
            this.DeleteLessonAdmin = this.DeleteLessonAdmin.bind(this)
            this.DeleteQuestionAdmin = this.DeleteQuestionAdmin.bind(this)
            this.DeleteQuestionAudio = this.DeleteQuestionAudio.bind(this)
            this.DeleteUnitAdmin = this.DeleteUnitAdmin.bind(this)
            this.GetLesson = this.GetLesson.bind(this)
            this.GetQuestion = this.GetQuestion.bind(this)
            this.GetQuestionAudioURL = this.GetQuestionAudioURL.bind(this)
            this.GetUnit = this.GetUnit.bind(this)
            this.ListLessons = this.ListLessons.bind(this)
            this.ListQuestions = this.ListQuestions.bind(this)
            this.ListUnits = this.ListUnits.bind(this)
            this.UpdateLessonAdmin = this.UpdateLessonAdmin.bind(this)
            this.UpdateQuestionAdmin = this.UpdateQuestionAdmin.bind(this)
            this.UpdateUnitAdmin = this.UpdateUnitAdmin.bind(this)
            this.UploadQuestionAudio = this.UploadQuestionAudio.bind(this)
        }

        /**
         * CreateLessonAdmin creates a new lesson (admin only).
         */
        public async CreateLessonAdmin(params: CreateLessonParams): Promise<LessonResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/admin/lessons`, JSON.stringify(params))
            return await resp.json() as LessonResponse
        }

        /**
         * CreateQuestionAdmin creates a new question (admin only).
         */
        public async CreateQuestionAdmin(params: CreateQuestionParams): Promise<QuestionResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/admin/questions`, JSON.stringify(params))
            return await resp.json() as QuestionResponse
        }

        /**
         * CreateUnitAdmin creates a new unit (admin only).
         */
        public async CreateUnitAdmin(params: CreateUnitParams): Promise<UnitResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/admin/units`, JSON.stringify(params))
            return await resp.json() as UnitResponse
        }

        /**
         * DeleteLessonAdmin deletes a lesson (admin only).
         */
        public async DeleteLessonAdmin(id: string): Promise<DeleteLessonResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("DELETE", `/admin/lessons/${encodeURIComponent(id)}`)
            return await resp.json() as DeleteLessonResponse
        }

        /**
         * DeleteQuestionAdmin deletes a question (admin only).
         */
        public async DeleteQuestionAdmin(id: string): Promise<DeleteQuestionResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("DELETE", `/admin/questions/${encodeURIComponent(id)}`)
            return await resp.json() as DeleteQuestionResponse
        }

        /**
         * DeleteQuestionAudio deletes audio for a question (admin only).
         */
        public async DeleteQuestionAudio(questionID: string): Promise<DeleteQuestionResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("DELETE", `/admin/questions/${encodeURIComponent(questionID)}/audio`)
            return await resp.json() as DeleteQuestionResponse
        }

        /**
         * DeleteUnitAdmin deletes a unit (admin only).
         */
        public async DeleteUnitAdmin(id: string): Promise<DeleteUnitResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("DELETE", `/admin/units/${encodeURIComponent(id)}`)
            return await resp.json() as DeleteUnitResponse
        }

        /**
         * GetLesson returns a specific lesson by ID.
         */
        public async GetLesson(id: string): Promise<LessonResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/lessons/${encodeURIComponent(id)}`)
            return await resp.json() as LessonResponse
        }

        /**
         * GetQuestion returns a specific question by ID.
         */
        public async GetQuestion(id: string): Promise<QuestionResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/questions/${encodeURIComponent(id)}`)
            return await resp.json() as QuestionResponse
        }

        /**
         * GetQuestionAudioURL returns a signed URL for audio playback.
         */
        public async GetQuestionAudioURL(questionID: string): Promise<AudioURLResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/questions/${encodeURIComponent(questionID)}/audio`)
            return await resp.json() as AudioURLResponse
        }

        /**
         * GetUnit returns a specific unit by ID.
         */
        public async GetUnit(id: string): Promise<UnitResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/units/${encodeURIComponent(id)}`)
            return await resp.json() as UnitResponse
        }

        /**
         * ListLessons returns all lessons for a unit.
         */
        public async ListLessons(unitID: string): Promise<LessonsResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/units/${encodeURIComponent(unitID)}/lessons`)
            return await resp.json() as LessonsResponse
        }

        /**
         * ListQuestions returns all questions for a lesson.
         */
        public async ListQuestions(lessonID: string): Promise<QuestionsResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/lessons/${encodeURIComponent(lessonID)}/questions`)
            return await resp.json() as QuestionsResponse
        }

        /**
         * ListUnits returns all units for a language.
         */
        public async ListUnits(languageID: string): Promise<UnitsResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/languages/${encodeURIComponent(languageID)}/units`)
            return await resp.json() as UnitsResponse
        }

        /**
         * UpdateLessonAdmin updates an existing lesson (admin only).
         */
        public async UpdateLessonAdmin(id: string, params: UpdateLessonParams): Promise<LessonResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("PUT", `/admin/lessons/${encodeURIComponent(id)}`, JSON.stringify(params))
            return await resp.json() as LessonResponse
        }

        /**
         * UpdateQuestionAdmin updates an existing question (admin only).
         */
        public async UpdateQuestionAdmin(id: string, params: UpdateQuestionParams): Promise<QuestionResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("PUT", `/admin/questions/${encodeURIComponent(id)}`, JSON.stringify(params))
            return await resp.json() as QuestionResponse
        }

        /**
         * UpdateUnitAdmin updates an existing unit (admin only).
         */
        public async UpdateUnitAdmin(id: string, params: UpdateUnitParams): Promise<UnitResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("PUT", `/admin/units/${encodeURIComponent(id)}`, JSON.stringify(params))
            return await resp.json() as UnitResponse
        }

        /**
         * UploadQuestionAudio uploads audio for a question (admin only).
         */
        public async UploadQuestionAudio(questionID: string, params: AudioUploadRequest): Promise<AudioUploadResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/admin/questions/${encodeURIComponent(questionID)}/audio`, JSON.stringify(params))
            return await resp.json() as AudioUploadResponse
        }
    }
}

export namespace dashboard {
    /**
     * CompletionStats contains lesson completion statistics.
     */
    export interface CompletionStats {
        "total_completions": number
        "completions_today": number
        "completions_week": number
        "average_score": number
        "completion_rate": number
        "completion_trend": DailyCount[]
    }

    /**
     * CompletionStatsResponse wraps completion stats.
     */
    export interface CompletionStatsResponse {
        stats: CompletionStats
    }

    /**
     * ContentStats contains content statistics.
     */
    export interface ContentStats {
        "total_languages": number
        "active_languages": number
        "total_units": number
        "total_lessons": number
        "total_questions": number
        "questions_with_audio": number
    }

    /**
     * ContentStatsResponse wraps content stats.
     */
    export interface ContentStatsResponse {
        stats: ContentStats
    }

    /**
     * DailyCount represents a count for a specific day.
     */
    export interface DailyCount {
        date: string
        count: number
    }

    /**
     * EnrollmentStats contains enrollment statistics.
     */
    export interface EnrollmentStats {
        "total_enrollments": number
        "active_enrollments": number
        "enrollments_by_language": LanguageEnrollment[]
        "enrollment_trend": DailyCount[]
    }

    /**
     * EnrollmentStatsResponse wraps enrollment stats.
     */
    export interface EnrollmentStatsResponse {
        stats: EnrollmentStats
    }

    /**
     * LanguageEnrollment represents enrollments for a language.
     */
    export interface LanguageEnrollment {
        "language_id": string
        "language_name": string
        "language_code": string
        count: number
    }

    /**
     * OverviewResponse wraps overview stats.
     */
    export interface OverviewResponse {
        stats: OverviewStats
        "updated_at": string
    }

    /**
     * OverviewStats contains high-level platform statistics.
     */
    export interface OverviewStats {
        "total_users": number
        "total_languages": number
        "active_users_today": number
        "active_users_week": number
        "active_users_month": number
        "total_enrollments": number
        "total_lessons": number
        "total_questions": number
        "lessons_completed_today": number
    }

    /**
     * PingResponse contains health check result.
     */
    export interface PingResponse {
        status: string
        timestamp: string
    }

    /**
     * StreakStats contains streak-related statistics.
     */
    export interface StreakStats {
        "users_with_streak": number
        "average_streak": number
        "longest_streak": number
        "goal_completion_rate": number
    }

    /**
     * StreakStatsResponse wraps streak stats.
     */
    export interface StreakStatsResponse {
        stats: StreakStats
    }

    /**
     * UserStats contains user-related statistics.
     */
    export interface UserStats {
        "total_users": number
        "new_users_today": number
        "new_users_week": number
        "new_users_month": number
        "users_by_provider": { [key: string]: number }
        "signup_trend": DailyCount[]
    }

    /**
     * UserStatsResponse wraps user stats.
     */
    export interface UserStatsResponse {
        stats: UserStats
    }

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.GetCompletionAnalytics = this.GetCompletionAnalytics.bind(this)
            this.GetContentAnalytics = this.GetContentAnalytics.bind(this)
            this.GetEnrollmentAnalytics = this.GetEnrollmentAnalytics.bind(this)
            this.GetOverview = this.GetOverview.bind(this)
            this.GetStreakAnalytics = this.GetStreakAnalytics.bind(this)
            this.GetUserAnalytics = this.GetUserAnalytics.bind(this)
            this.Ping = this.Ping.bind(this)
        }

        /**
         * GetCompletionAnalytics returns lesson completion statistics.
         */
        public async GetCompletionAnalytics(): Promise<CompletionStatsResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/admin/analytics/completion`)
            return await resp.json() as CompletionStatsResponse
        }

        /**
         * GetContentAnalytics returns content statistics.
         */
        public async GetContentAnalytics(): Promise<ContentStatsResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/admin/analytics/content`)
            return await resp.json() as ContentStatsResponse
        }

        /**
         * GetEnrollmentAnalytics returns enrollment statistics.
         */
        public async GetEnrollmentAnalytics(): Promise<EnrollmentStatsResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/admin/analytics/enrollments`)
            return await resp.json() as EnrollmentStatsResponse
        }

        /**
         * GetOverview returns high-level platform statistics.
         */
        public async GetOverview(): Promise<OverviewResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/admin/analytics/overview`)
            return await resp.json() as OverviewResponse
        }

        /**
         * GetStreakAnalytics returns streak-related statistics.
         */
        public async GetStreakAnalytics(): Promise<StreakStatsResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/admin/analytics/streaks`)
            return await resp.json() as StreakStatsResponse
        }

        /**
         * GetUserAnalytics returns user-related statistics.
         */
        public async GetUserAnalytics(): Promise<UserStatsResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/admin/analytics/users`)
            return await resp.json() as UserStatsResponse
        }

        /**
         * Ping is a simple health check endpoint.
         */
        public async Ping(): Promise<PingResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/admin/health`)
            return await resp.json() as PingResponse
        }
    }
}

export namespace enrollment {
    /**
     * EnrollRequest contains the language to enroll in.
     */
    export interface EnrollRequest {
        "language_id": string
    }

    /**
     * Enrollment represents a user's enrollment in a language.
     */
    export interface Enrollment {
        id: uuid.UUID
        "user_id": uuid.UUID
        "language_id": uuid.UUID
        "is_active": boolean
        "enrolled_at": string
        "updated_at": string
    }

    /**
     * EnrollmentCheckResponse indicates enrollment status.
     */
    export interface EnrollmentCheckResponse {
        enrolled: boolean
    }

    /**
     * EnrollmentResponse wraps a single enrollment.
     */
    export interface EnrollmentResponse {
        enrollment: Enrollment
    }

    /**
     * EnrollmentWithLanguage includes language details.
     */
    export interface EnrollmentWithLanguage {
        "language_name": string
        "language_code": string
        "language_emoji": string
    }

    /**
     * EnrollmentsResponse wraps a list of enrollments.
     */
    export interface EnrollmentsResponse {
        enrollments: EnrollmentWithLanguage[]
    }

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.CheckEnrollment = this.CheckEnrollment.bind(this)
            this.Enroll = this.Enroll.bind(this)
            this.ListEnrollments = this.ListEnrollments.bind(this)
            this.UnenrollFromLanguage = this.UnenrollFromLanguage.bind(this)
        }

        /**
         * CheckEnrollment checks if the current user is enrolled in a language.
         */
        public async CheckEnrollment(languageID: string): Promise<EnrollmentCheckResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/enroll/${encodeURIComponent(languageID)}/check`)
            return await resp.json() as EnrollmentCheckResponse
        }

        /**
         * Enroll enrolls the current user in a language.
         */
        public async Enroll(params: EnrollRequest): Promise<EnrollmentResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/enroll`, JSON.stringify(params))
            return await resp.json() as EnrollmentResponse
        }

        /**
         * ListEnrollments lists all languages the current user is enrolled in.
         */
        public async ListEnrollments(): Promise<EnrollmentsResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/enrollments`)
            return await resp.json() as EnrollmentsResponse
        }

        /**
         * Unenroll removes the current user from a language.
         */
        public async UnenrollFromLanguage(languageID: string): Promise<EnrollmentResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("DELETE", `/enroll/${encodeURIComponent(languageID)}`)
            return await resp.json() as EnrollmentResponse
        }
    }
}

export namespace language {
    /**
     * CreateLanguageParams contains parameters for creating a language.
     */
    export interface CreateLanguageParams {
        name: string
        code: string
        description: string
        "flag_emoji": string
    }

    /**
     * DeleteLanguageResponse is returned after deleting a language.
     */
    export interface DeleteLanguageResponse {
        success: boolean
    }

    /**
     * Language represents a learnable language on the platform.
     */
    export interface Language {
        id: uuid.UUID
        /**
         * e.g., "Yoruba", "Igbo", "Hausa"
         */
        name: string

        /**
         * ISO 639-1 code: "yo", "ig", "ha"
         */
        code: string

        description: string
        "flag_emoji": string
        "is_active": boolean
        "created_at": string
        "updated_at": string
    }

    /**
     * LanguageResponse wraps a single language.
     */
    export interface LanguageResponse {
        language: Language
    }

    /**
     * LanguagesResponse wraps a list of languages.
     */
    export interface LanguagesResponse {
        languages: Language[]
    }

    /**
     * UpdateLanguageParams contains parameters for updating a language.
     */
    export interface UpdateLanguageParams {
        name: string
        code: string
        description: string
        "flag_emoji": string
        "is_active": boolean
    }

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.CreateLanguage = this.CreateLanguage.bind(this)
            this.DeleteLanguage = this.DeleteLanguage.bind(this)
            this.GetLanguage = this.GetLanguage.bind(this)
            this.ListAllLanguages = this.ListAllLanguages.bind(this)
            this.ListLanguages = this.ListLanguages.bind(this)
            this.UpdateLanguage = this.UpdateLanguage.bind(this)
        }

        /**
         * CreateLanguage creates a new language (admin only).
         */
        public async CreateLanguage(params: CreateLanguageParams): Promise<LanguageResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/admin/languages`, JSON.stringify(params))
            return await resp.json() as LanguageResponse
        }

        /**
         * DeleteLanguage deletes a language (admin only).
         */
        public async DeleteLanguage(id: string): Promise<DeleteLanguageResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("DELETE", `/admin/languages/${encodeURIComponent(id)}`)
            return await resp.json() as DeleteLanguageResponse
        }

        /**
         * GetLanguage returns a specific language by ID.
         */
        public async GetLanguage(id: string): Promise<LanguageResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/languages/${encodeURIComponent(id)}`)
            return await resp.json() as LanguageResponse
        }

        /**
         * ListAllLanguages returns all languages including inactive ones (admin only).
         */
        public async ListAllLanguages(): Promise<LanguagesResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/admin/languages`)
            return await resp.json() as LanguagesResponse
        }

        /**
         * ListLanguages returns all active languages available for learning.
         */
        public async ListLanguages(): Promise<LanguagesResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/languages`)
            return await resp.json() as LanguagesResponse
        }

        /**
         * UpdateLanguage updates an existing language (admin only).
         */
        public async UpdateLanguage(id: string, params: UpdateLanguageParams): Promise<LanguageResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("PUT", `/admin/languages/${encodeURIComponent(id)}`, JSON.stringify(params))
            return await resp.json() as LanguageResponse
        }
    }
}

export namespace lesson {
    /**
     * CompleteSessionResponse is returned when completing a session.
     */
    export interface CompleteSessionResponse {
        session: LessonSession
        "total_xp": number
        accuracy: number
        "correct_count": number
        "total_count": number
    }

    /**
     * LessonSession represents an active or completed lesson attempt.
     */
    export interface LessonSession {
        id: uuid.UUID
        "user_id": uuid.UUID
        "lesson_id": uuid.UUID
        status: SessionStatus
        "current_index": number
        "correct_count": number
        "incorrect_count": number
        "xp_earned": number
        "started_at": string
        "completed_at": string
        "updated_at": string
    }

    /**
     * ListSessionsParams contains pagination parameters.
     */
    export interface ListSessionsParams {
        Limit: number
        Offset: number
    }

    /**
     * QuestionInfo contains question data for the client (without correct answer).
     */
    export interface QuestionInfo {
        id: uuid.UUID
        type: string
        "prompt_text": string
        "has_audio": boolean
        "use_tts": boolean
        options: string[]
        hint: string
        "sort_order": number
    }

    /**
     * SessionResponse wraps a single session.
     */
    export interface SessionResponse {
        session: LessonSession
    }

    /**
     * SessionStatus represents the status of a lesson session.
     */
    export type SessionStatus = string

    /**
     * SessionsResponse wraps a list of sessions.
     */
    export interface SessionsResponse {
        sessions: LessonSession[]
    }

    /**
     * StartSessionResponse is returned when starting a new lesson session.
     */
    export interface StartSessionResponse {
        session: LessonSession
        questions: QuestionInfo[]
    }

    /**
     * SubmitAnswerRequest contains the user's answer to a question.
     */
    export interface SubmitAnswerRequest {
        "question_id": string
        answer: string
    }

    /**
     * SubmitAnswerResponse is returned after evaluating an answer.
     */
    export interface SubmitAnswerResponse {
        "is_correct": boolean
        "correct_answer": string
        similarity: number
        hint: string
        "xp_earned": number
    }

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.AbandonLesson = this.AbandonLesson.bind(this)
            this.CompleteLesson = this.CompleteLesson.bind(this)
            this.GetSession = this.GetSession.bind(this)
            this.ListMySessions = this.ListMySessions.bind(this)
            this.StartLesson = this.StartLesson.bind(this)
            this.SubmitAnswer = this.SubmitAnswer.bind(this)
        }

        /**
         * AbandonLesson abandons an in-progress lesson session.
         */
        public async AbandonLesson(sessionID: string): Promise<SessionResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/sessions/${encodeURIComponent(sessionID)}/abandon`)
            return await resp.json() as SessionResponse
        }

        /**
         * CompleteLesson completes a lesson session.
         */
        public async CompleteLesson(sessionID: string): Promise<CompleteSessionResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/sessions/${encodeURIComponent(sessionID)}/complete`)
            return await resp.json() as CompleteSessionResponse
        }

        /**
         * GetSession retrieves a session by ID.
         */
        public async GetSession(sessionID: string): Promise<SessionResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/sessions/${encodeURIComponent(sessionID)}`)
            return await resp.json() as SessionResponse
        }

        /**
         * ListMySessions lists the current user's lesson sessions.
         */
        public async ListMySessions(params: ListSessionsParams): Promise<SessionsResponse> {
            // Convert our params into the objects we need for the request
            const query = makeRecord<string, string | string[]>({
                limit:  String(params.Limit),
                offset: String(params.Offset),
            })

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/sessions`, undefined, {query})
            return await resp.json() as SessionsResponse
        }

        /**
         * StartLesson starts a new lesson session or resumes an existing one.
         */
        public async StartLesson(lessonID: string): Promise<StartSessionResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/lessons/${encodeURIComponent(lessonID)}/start`)
            return await resp.json() as StartSessionResponse
        }

        /**
         * SubmitAnswer submits an answer for the current question in a session.
         */
        public async SubmitAnswer(sessionID: string, params: SubmitAnswerRequest): Promise<SubmitAnswerResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/sessions/${encodeURIComponent(sessionID)}/answer`, JSON.stringify(params))
            return await resp.json() as SubmitAnswerResponse
        }
    }
}

export namespace streak {
    /**
     * ActivityHistoryResponse contains recent activity.
     */
    export interface ActivityHistoryResponse {
        activities: DailyActivity[]
        days: number
    }

    /**
     * DailyActivity tracks a user's activity for a specific day.
     */
    export interface DailyActivity {
        id: uuid.UUID
        "user_id": uuid.UUID
        date: string
        "xp_earned": number
        "lessons_completed": number
        "goal_met": boolean
        "created_at": string
    }

    /**
     * DailyGoalResponse contains today's progress.
     */
    export interface DailyGoalResponse {
        "daily_xp_goal": number
        "today_xp": number
        "today_lessons": number
        "goal_met": boolean
        "xp_remaining": number
        "percent_complete": number
    }

    /**
     * Streak tracks a user's daily learning streak.
     */
    export interface Streak {
        id: uuid.UUID
        "user_id": uuid.UUID
        "current_streak": number
        "longest_streak": number
        "last_active_date": string
        "daily_xp_goal": number
        "streak_freezes": number
        "updated_at": string
    }

    /**
     * StreakResponse wraps streak data.
     */
    export interface StreakResponse {
        streak: Streak
        "today_xp": number
        "today_lessons": number
        "goal_met": boolean
        "xp_to_goal": number
        "streak_at_risk": boolean
    }

    /**
     * UpdateGoalRequest contains new goal settings.
     */
    export interface UpdateGoalRequest {
        "daily_xp_goal": number
    }

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.GetActivityHistory = this.GetActivityHistory.bind(this)
            this.GetDailyGoal = this.GetDailyGoal.bind(this)
            this.GetMyStreak = this.GetMyStreak.bind(this)
            this.UpdateDailyGoal = this.UpdateDailyGoal.bind(this)
        }

        /**
         * GetActivityHistory returns recent daily activity.
         */
        public async GetActivityHistory(): Promise<ActivityHistoryResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/activity`)
            return await resp.json() as ActivityHistoryResponse
        }

        /**
         * GetDailyGoal returns today's progress toward the daily goal.
         */
        public async GetDailyGoal(): Promise<DailyGoalResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/daily-goal`)
            return await resp.json() as DailyGoalResponse
        }

        /**
         * GetMyStreak returns the current user's streak information.
         */
        public async GetMyStreak(): Promise<StreakResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/streak`)
            return await resp.json() as StreakResponse
        }

        /**
         * UpdateDailyGoal updates the user's daily XP goal.
         */
        public async UpdateDailyGoal(params: UpdateGoalRequest): Promise<StreakResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("PUT", `/daily-goal`, JSON.stringify(params))
            return await resp.json() as StreakResponse
        }
    }
}

export namespace tracker {
    /**
     * LessonProgress tracks a user's progress on a specific lesson.
     */
    export interface LessonProgress {
        id: uuid.UUID
        "user_id": uuid.UUID
        "lesson_id": uuid.UUID
        status: ProgressStatus
        "xp_earned": number
        attempts: number
        "best_score": number
        "completed_at": string
        "updated_at": string
    }

    /**
     * ListMistakesParams contains pagination parameters.
     */
    export interface ListMistakesParams {
        Limit: number
        Offset: number
    }

    /**
     * MarkReviewedRequest contains the mistake ID to mark.
     */
    export interface MarkReviewedRequest {
        "mistake_id": string
    }

    /**
     * MarkReviewedResponse indicates success.
     */
    export interface MarkReviewedResponse {
        success: boolean
    }

    /**
     * MistakeWithQuestion includes question details.
     */
    export interface MistakeWithQuestion {
        "prompt_text": string
        hint: string
    }

    /**
     * MistakesResponse wraps a list of mistakes.
     */
    export interface MistakesResponse {
        mistakes: MistakeWithQuestion[]
        total: number
    }

    /**
     * ProgressListResponse wraps a list of progress entries.
     */
    export interface ProgressListResponse {
        progress: LessonProgress[]
    }

    /**
     * ProgressResponse wraps lesson progress.
     */
    export interface ProgressResponse {
        progress: LessonProgress
    }

    /**
     * ProgressStatus represents the status of lesson progress.
     */
    export type ProgressStatus = string

    /**
     * UserStatsResponse contains user statistics.
     */
    export interface UserStatsResponse {
        "total_xp": number
        "lessons_completed": number
        "lessons_in_progress": number
        "total_mistakes": number
        "unreviewed_mistakes": number
        "average_score": number
    }

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.GetLessonProgress = this.GetLessonProgress.bind(this)
            this.GetMyStats = this.GetMyStats.bind(this)
            this.ListMistakesByLanguageEndpoint = this.ListMistakesByLanguageEndpoint.bind(this)
            this.ListMyMistakes = this.ListMyMistakes.bind(this)
            this.ListMyProgress = this.ListMyProgress.bind(this)
            this.MarkMistakeAsReviewed = this.MarkMistakeAsReviewed.bind(this)
        }

        /**
         * GetLessonProgress returns progress for a specific lesson.
         */
        public async GetLessonProgress(lessonID: string): Promise<ProgressResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/progress/lessons/${encodeURIComponent(lessonID)}`)
            return await resp.json() as ProgressResponse
        }

        /**
         * GetMyStats returns statistics for the current user.
         */
        public async GetMyStats(): Promise<UserStatsResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/stats`)
            return await resp.json() as UserStatsResponse
        }

        /**
         * ListMistakesByLanguageEndpoint lists mistakes for a specific language.
         */
        public async ListMistakesByLanguageEndpoint(languageID: string, params: ListMistakesParams): Promise<MistakesResponse> {
            // Convert our params into the objects we need for the request
            const query = makeRecord<string, string | string[]>({
                limit:  String(params.Limit),
                offset: String(params.Offset),
            })

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/mistakes/${encodeURIComponent(languageID)}`, undefined, {query})
            return await resp.json() as MistakesResponse
        }

        /**
         * ListMyMistakes lists all mistakes for the current user.
         */
        public async ListMyMistakes(params: ListMistakesParams): Promise<MistakesResponse> {
            // Convert our params into the objects we need for the request
            const query = makeRecord<string, string | string[]>({
                limit:  String(params.Limit),
                offset: String(params.Offset),
            })

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/mistakes`, undefined, {query})
            return await resp.json() as MistakesResponse
        }

        /**
         * ListMyProgress lists all progress for the current user.
         */
        public async ListMyProgress(): Promise<ProgressListResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/progress`)
            return await resp.json() as ProgressListResponse
        }

        /**
         * MarkMistakeAsReviewed marks a mistake as reviewed.
         */
        public async MarkMistakeAsReviewed(params: MarkReviewedRequest): Promise<MarkReviewedResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/mistakes/review`, JSON.stringify(params))
            return await resp.json() as MarkReviewedResponse
        }
    }
}

export namespace user {
    /**
     * DeleteUserResponse is returned after deleting a user
     */
    export interface DeleteUserResponse {
        success: boolean
    }

    /**
     * ListUsersParams contains pagination parameters
     */
    export interface ListUsersParams {
        Limit: number
        Offset: number
    }

    /**
     * Provider represents the authentication provider
     */
    export type Provider = string

    /**
     * Role represents user authorization level
     */
    export type Role = string

    /**
     * UpdateCurrentUserParams contains the update parameters
     */
    export interface UpdateCurrentUserParams {
        name: string
        "avatar_url": string
    }

    /**
     * UpdateUserRoleBody contains the role to update
     */
    export interface UpdateUserRoleBody {
        role: Role
    }

    /**
     * User represents a user in the system
     */
    export interface User {
        id: uuid.UUID
        provider: Provider
        "provider_id": string
        email: string
        name: string
        "avatar_url": string
        role: Role
        "created_at": string
        "updated_at": string
    }

    /**
     * UserResponse is the API response for user data
     */
    export interface UserResponse {
        user: User
    }

    /**
     * UsersResponse is the API response for multiple users
     */
    export interface UsersResponse {
        users: User[]
        total: number
    }

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.DeleteUser = this.DeleteUser.bind(this)
            this.GetCurrentUser = this.GetCurrentUser.bind(this)
            this.GetUser = this.GetUser.bind(this)
            this.ListUsers = this.ListUsers.bind(this)
            this.UpdateCurrentUser = this.UpdateCurrentUser.bind(this)
            this.UpdateUserRole = this.UpdateUserRole.bind(this)
        }

        /**
         * DeleteUser deletes a user by ID (admin only).
         */
        public async DeleteUser(id: string): Promise<DeleteUserResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("DELETE", `/admin/users/${encodeURIComponent(id)}`)
            return await resp.json() as DeleteUserResponse
        }

        /**
         * GetCurrentUser returns the currently authenticated user's profile.
         */
        public async GetCurrentUser(): Promise<UserResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/users/me`)
            return await resp.json() as UserResponse
        }

        /**
         * GetUser returns a user by ID (admin only).
         */
        public async GetUser(id: string): Promise<UserResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/admin/users/${encodeURIComponent(id)}`)
            return await resp.json() as UserResponse
        }

        /**
         * ListUsers returns a paginated list of users (admin only).
         */
        public async ListUsers(params: ListUsersParams): Promise<UsersResponse> {
            // Convert our params into the objects we need for the request
            const query = makeRecord<string, string | string[]>({
                limit:  String(params.Limit),
                offset: String(params.Offset),
            })

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/admin/users`, undefined, {query})
            return await resp.json() as UsersResponse
        }

        /**
         * UpdateCurrentUser updates the currently authenticated user's profile.
         */
        public async UpdateCurrentUser(params: UpdateCurrentUserParams): Promise<UserResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("PATCH", `/users/me`, JSON.stringify(params))
            return await resp.json() as UserResponse
        }

        /**
         * UpdateUserRole updates a user's role (admin only).
         */
        public async UpdateUserRole(id: string, params: UpdateUserRoleBody): Promise<UserResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("PATCH", `/admin/users/${encodeURIComponent(id)}/role`, JSON.stringify(params))
            return await resp.json() as UserResponse
        }
    }
}

export namespace uuid {
    /**
     * A UUID is a 128 bit (16 byte) Universal Unique IDentifier as defined in RFC
     * 4122.
     */
    export type UUID = string
}



function encodeQuery(parts: Record<string, string | string[]>): string {
    const pairs: string[] = []
    for (const key in parts) {
        const val = (Array.isArray(parts[key]) ?  parts[key] : [parts[key]]) as string[]
        for (const v of val) {
            pairs.push(`${key}=${encodeURIComponent(v)}`)
        }
    }
    return pairs.join("&")
}

// makeRecord takes a record and strips any undefined values from it,
// and returns the same record with a narrower type.
// @ts-ignore - TS ignore because makeRecord is not always used
function makeRecord<K extends string | number | symbol, V>(record: Record<K, V | undefined>): Record<K, V> {
    for (const key in record) {
        if (record[key] === undefined) {
            delete record[key]
        }
    }
    return record as Record<K, V>
}

function encodeWebSocketHeaders(headers: Record<string, string>) {
    // url safe, no pad
    const base64encoded = btoa(JSON.stringify(headers))
      .replaceAll("=", "")
      .replaceAll("+", "-")
      .replaceAll("/", "_");
    return "encore.dev.headers." + base64encoded;
}

class WebSocketConnection {
    public ws: WebSocket;

    private hasUpdateHandlers: (() => void)[] = [];

    constructor(url: string, headers?: Record<string, string>) {
        let protocols = ["encore-ws"];
        if (headers) {
            protocols.push(encodeWebSocketHeaders(headers))
        }

        this.ws = new WebSocket(url, protocols)

        this.on("error", () => {
            this.resolveHasUpdateHandlers();
        });

        this.on("close", () => {
            this.resolveHasUpdateHandlers();
        });
    }

    resolveHasUpdateHandlers() {
        const handlers = this.hasUpdateHandlers;
        this.hasUpdateHandlers = [];

        for (const handler of handlers) {
            handler()
        }
    }

    async hasUpdate() {
        // await until a new message have been received, or the socket is closed
        await new Promise((resolve) => {
            this.hasUpdateHandlers.push(() => resolve(null))
        });
    }

    on(type: "error" | "close" | "message" | "open", handler: (event: any) => void) {
        this.ws.addEventListener(type, handler);
    }

    off(type: "error" | "close" | "message" | "open", handler: (event: any) => void) {
        this.ws.removeEventListener(type, handler);
    }

    close() {
        this.ws.close();
    }
}

export class StreamInOut<Request, Response> {
    public socket: WebSocketConnection;
    private buffer: Response[] = [];

    constructor(url: string, headers?: Record<string, string>) {
        this.socket = new WebSocketConnection(url, headers);
        this.socket.on("message", (event: any) => {
            this.buffer.push(JSON.parse(event.data));
            this.socket.resolveHasUpdateHandlers();
        });
    }

    close() {
        this.socket.close();
    }

    async send(msg: Request) {
        if (this.socket.ws.readyState === WebSocket.CONNECTING) {
            // await that the socket is opened
            await new Promise((resolve) => {
                this.socket.ws.addEventListener("open", resolve, { once: true });
            });
        }

        return this.socket.ws.send(JSON.stringify(msg));
    }

    async next(): Promise<Response | undefined> {
        for await (const next of this) return next;
        return undefined;
    }

    async *[Symbol.asyncIterator](): AsyncGenerator<Response, undefined, void> {
        while (true) {
            if (this.buffer.length > 0) {
                yield this.buffer.shift() as Response;
            } else {
                if (this.socket.ws.readyState === WebSocket.CLOSED) return;
                await this.socket.hasUpdate();
            }
        }
    }
}

export class StreamIn<Response> {
    public socket: WebSocketConnection;
    private buffer: Response[] = [];

    constructor(url: string, headers?: Record<string, string>) {
        this.socket = new WebSocketConnection(url, headers);
        this.socket.on("message", (event: any) => {
            this.buffer.push(JSON.parse(event.data));
            this.socket.resolveHasUpdateHandlers();
        });
    }

    close() {
        this.socket.close();
    }

    async next(): Promise<Response | undefined> {
        for await (const next of this) return next;
        return undefined;
    }

    async *[Symbol.asyncIterator](): AsyncGenerator<Response, undefined, void> {
        while (true) {
            if (this.buffer.length > 0) {
                yield this.buffer.shift() as Response;
            } else {
                if (this.socket.ws.readyState === WebSocket.CLOSED) return;
                await this.socket.hasUpdate();
            }
        }
    }
}

export class StreamOut<Request, Response> {
    public socket: WebSocketConnection;
    private responseValue: Promise<Response>;

    constructor(url: string, headers?: Record<string, string>) {
        let responseResolver: (_: any) => void;
        this.responseValue = new Promise((resolve) => responseResolver = resolve);

        this.socket = new WebSocketConnection(url, headers);
        this.socket.on("message", (event: any) => {
            responseResolver(JSON.parse(event.data))
        });
    }

    async response(): Promise<Response> {
        return this.responseValue;
    }

    close() {
        this.socket.close();
    }

    async send(msg: Request) {
        if (this.socket.ws.readyState === WebSocket.CONNECTING) {
            // await that the socket is opened
            await new Promise((resolve) => {
                this.socket.ws.addEventListener("open", resolve, { once: true });
            });
        }

        return this.socket.ws.send(JSON.stringify(msg));
    }
}
// CallParameters is the type of the parameters to a method call, but require headers to be a Record type
type CallParameters = Omit<RequestInit, "method" | "body" | "headers"> & {
    /** Headers to be sent with the request */
    headers?: Record<string, string>

    /** Query parameters to be sent with the request */
    query?: Record<string, string | string[]>
}

// AuthDataGenerator is a function that returns a new instance of the authentication data required by this API
export type AuthDataGenerator = () =>
  | auth.AuthParams
  | Promise<auth.AuthParams | undefined>
  | undefined;

// A fetcher is the prototype for the inbuilt Fetch function
export type Fetcher = typeof fetch;

const boundFetch = fetch.bind(this);

class BaseClient {
    readonly baseURL: string
    readonly fetcher: Fetcher
    readonly headers: Record<string, string>
    readonly requestInit: Omit<RequestInit, "headers"> & { headers?: Record<string, string> }
    readonly authGenerator?: AuthDataGenerator

    constructor(baseURL: string, options: ClientOptions) {
        this.baseURL = baseURL
        this.headers = {}

        // Add User-Agent header if the script is running in the server
        // because browsers do not allow setting User-Agent headers to requests
        if (!BROWSER) {
            this.headers["User-Agent"] = "bawo-wwb2-Generated-TS-Client (Encore/v1.54.0)";
        }

        this.requestInit = options.requestInit ?? {};

        // Setup what fetch function we'll be using in the base client
        if (options.fetcher !== undefined) {
            this.fetcher = options.fetcher
        } else {
            this.fetcher = boundFetch
        }

        // Setup an authentication data generator using the auth data token option
        if (options.auth !== undefined) {
            const auth = options.auth
            if (typeof auth === "function") {
                this.authGenerator = auth
            } else {
                this.authGenerator = () => auth
            }
        }
    }

    async getAuthData(): Promise<CallParameters | undefined> {
        let authData: auth.AuthParams | undefined;

        // If authorization data generator is present, call it and add the returned data to the request
        if (this.authGenerator) {
            const mayBePromise = this.authGenerator();
            if (mayBePromise instanceof Promise) {
                authData = await mayBePromise;
            } else {
                authData = mayBePromise;
            }
        }

        if (authData) {
            const data: CallParameters = {};

            data.headers = makeRecord<string, string>({
                authorization: authData.Authorization,
            });

            return data;
        }

        return undefined;
    }

    // createStreamInOut sets up a stream to a streaming API endpoint.
    async createStreamInOut<Request, Response>(path: string, params?: CallParameters): Promise<StreamInOut<Request, Response>> {
        let { query, headers } = params ?? {};

        // Fetch auth data if there is any
        const authData = await this.getAuthData();

        // If we now have authentication data, add it to the request
        if (authData) {
            if (authData.query) {
                query = {...query, ...authData.query};
            }
            if (authData.headers) {
                headers = {...headers, ...authData.headers};
            }
        }

        const queryString = query ? '?' + encodeQuery(query) : ''
        return new StreamInOut(this.baseURL + path + queryString, headers);
    }

    // createStreamIn sets up a stream to a streaming API endpoint.
    async createStreamIn<Response>(path: string, params?: CallParameters): Promise<StreamIn<Response>> {
        let { query, headers } = params ?? {};

        // Fetch auth data if there is any
        const authData = await this.getAuthData();

        // If we now have authentication data, add it to the request
        if (authData) {
            if (authData.query) {
                query = {...query, ...authData.query};
            }
            if (authData.headers) {
                headers = {...headers, ...authData.headers};
            }
        }

        const queryString = query ? '?' + encodeQuery(query) : ''
        return new StreamIn(this.baseURL + path + queryString, headers);
    }

    // createStreamOut sets up a stream to a streaming API endpoint.
    async createStreamOut<Request, Response>(path: string, params?: CallParameters): Promise<StreamOut<Request, Response>> {
        let { query, headers } = params ?? {};

        // Fetch auth data if there is any
        const authData = await this.getAuthData();

        // If we now have authentication data, add it to the request
        if (authData) {
            if (authData.query) {
                query = {...query, ...authData.query};
            }
            if (authData.headers) {
                headers = {...headers, ...authData.headers};
            }
        }

        const queryString = query ? '?' + encodeQuery(query) : ''
        return new StreamOut(this.baseURL + path + queryString, headers);
    }

    // callTypedAPI makes an API call, defaulting content type to "application/json"
    public async callTypedAPI(method: string, path: string, body?: RequestInit["body"], params?: CallParameters): Promise<Response> {
        return this.callAPI(method, path, body, {
            ...params,
            headers: { "Content-Type": "application/json", ...params?.headers }
        });
    }

    // callAPI is used by each generated API method to actually make the request
    public async callAPI(method: string, path: string, body?: RequestInit["body"], params?: CallParameters): Promise<Response> {
        let { query, headers, ...rest } = params ?? {}
        const init = {
            ...this.requestInit,
            ...rest,
            method,
            body: body ?? null,
        }

        // Merge our headers with any predefined headers
        init.headers = {...this.headers, ...init.headers, ...headers}

        // Fetch auth data if there is any
        const authData = await this.getAuthData();

        // If we now have authentication data, add it to the request
        if (authData) {
            if (authData.query) {
                query = {...query, ...authData.query};
            }
            if (authData.headers) {
                init.headers = {...init.headers, ...authData.headers};
            }
        }

        // Make the actual request
        const queryString = query ? '?' + encodeQuery(query) : ''
        const response = await this.fetcher(this.baseURL+path+queryString, init)

        // handle any error responses
        if (!response.ok) {
            // try and get the error message from the response body
            let body: APIErrorResponse = { code: ErrCode.Unknown, message: `request failed: status ${response.status}` }

            // if we can get the structured error we should, otherwise give a best effort
            try {
                const text = await response.text()

                try {
                    const jsonBody = JSON.parse(text)
                    if (isAPIErrorResponse(jsonBody)) {
                        body = jsonBody
                    } else {
                        body.message += ": " + JSON.stringify(jsonBody)
                    }
                } catch {
                    body.message += ": " + text
                }
            } catch (e) {
                // otherwise we just append the text to the error message
                body.message += ": " + String(e)
            }

            throw new APIError(response.status, body)
        }

        return response
    }
}

/**
 * APIErrorDetails represents the response from an Encore API in the case of an error
 */
interface APIErrorResponse {
    code: ErrCode
    message: string
    details?: any
}

function isAPIErrorResponse(err: any): err is APIErrorResponse {
    return (
        err !== undefined && err !== null &&
        isErrCode(err.code) &&
        typeof(err.message) === "string" &&
        (err.details === undefined || err.details === null || typeof(err.details) === "object")
    )
}

function isErrCode(code: any): code is ErrCode {
    return code !== undefined && Object.values(ErrCode).includes(code)
}

/**
 * APIError represents a structured error as returned from an Encore application.
 */
export class APIError extends Error {
    /**
     * The HTTP status code associated with the error.
     */
    public readonly status: number

    /**
     * The Encore error code
     */
    public readonly code: ErrCode

    /**
     * The error details
     */
    public readonly details?: any

    constructor(status: number, response: APIErrorResponse) {
        // extending errors causes issues after you construct them, unless you apply the following fixes
        super(response.message);

        // set error name as constructor name, make it not enumerable to keep native Error behavior
        // https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/new.target#new.target_in_constructors
        Object.defineProperty(this, 'name', {
            value:        'APIError',
            enumerable:   false,
            configurable: true,
        })

        // fix the prototype chain
        if ((Object as any).setPrototypeOf == undefined) {
            (this as any).__proto__ = APIError.prototype
        } else {
            Object.setPrototypeOf(this, APIError.prototype);
        }

        // capture a stack trace
        if ((Error as any).captureStackTrace !== undefined) {
            (Error as any).captureStackTrace(this, this.constructor);
        }

        this.status = status
        this.code = response.code
        this.details = response.details
    }
}

/**
 * Typeguard allowing use of an APIError's fields'
 */
export function isAPIError(err: any): err is APIError {
    return err instanceof APIError;
}

export enum ErrCode {
    /**
     * OK indicates the operation was successful.
     */
    OK = "ok",

    /**
     * Canceled indicates the operation was canceled (typically by the caller).
     *
     * Encore will generate this error code when cancellation is requested.
     */
    Canceled = "canceled",

    /**
     * Unknown error. An example of where this error may be returned is
     * if a Status value received from another address space belongs to
     * an error-space that is not known in this address space. Also
     * errors raised by APIs that do not return enough error information
     * may be converted to this error.
     *
     * Encore will generate this error code in the above two mentioned cases.
     */
    Unknown = "unknown",

    /**
     * InvalidArgument indicates client specified an invalid argument.
     * Note that this differs from FailedPrecondition. It indicates arguments
     * that are problematic regardless of the state of the system
     * (e.g., a malformed file name).
     *
     * This error code will not be generated by the gRPC framework.
     */
    InvalidArgument = "invalid_argument",

    /**
     * DeadlineExceeded means operation expired before completion.
     * For operations that change the state of the system, this error may be
     * returned even if the operation has completed successfully. For
     * example, a successful response from a server could have been delayed
     * long enough for the deadline to expire.
     *
     * The gRPC framework will generate this error code when the deadline is
     * exceeded.
     */
    DeadlineExceeded = "deadline_exceeded",

    /**
     * NotFound means some requested entity (e.g., file or directory) was
     * not found.
     *
     * This error code will not be generated by the gRPC framework.
     */
    NotFound = "not_found",

    /**
     * AlreadyExists means an attempt to create an entity failed because one
     * already exists.
     *
     * This error code will not be generated by the gRPC framework.
     */
    AlreadyExists = "already_exists",

    /**
     * PermissionDenied indicates the caller does not have permission to
     * execute the specified operation. It must not be used for rejections
     * caused by exhausting some resource (use ResourceExhausted
     * instead for those errors). It must not be
     * used if the caller cannot be identified (use Unauthenticated
     * instead for those errors).
     *
     * This error code will not be generated by the gRPC core framework,
     * but expect authentication middleware to use it.
     */
    PermissionDenied = "permission_denied",

    /**
     * ResourceExhausted indicates some resource has been exhausted, perhaps
     * a per-user quota, or perhaps the entire file system is out of space.
     *
     * This error code will be generated by the gRPC framework in
     * out-of-memory and server overload situations, or when a message is
     * larger than the configured maximum size.
     */
    ResourceExhausted = "resource_exhausted",

    /**
     * FailedPrecondition indicates operation was rejected because the
     * system is not in a state required for the operation's execution.
     * For example, directory to be deleted may be non-empty, an rmdir
     * operation is applied to a non-directory, etc.
     *
     * A litmus test that may help a service implementor in deciding
     * between FailedPrecondition, Aborted, and Unavailable:
     *  (a) Use Unavailable if the client can retry just the failing call.
     *  (b) Use Aborted if the client should retry at a higher-level
     *      (e.g., restarting a read-modify-write sequence).
     *  (c) Use FailedPrecondition if the client should not retry until
     *      the system state has been explicitly fixed. E.g., if an "rmdir"
     *      fails because the directory is non-empty, FailedPrecondition
     *      should be returned since the client should not retry unless
     *      they have first fixed up the directory by deleting files from it.
     *  (d) Use FailedPrecondition if the client performs conditional
     *      REST Get/Update/Delete on a resource and the resource on the
     *      server does not match the condition. E.g., conflicting
     *      read-modify-write on the same resource.
     *
     * This error code will not be generated by the gRPC framework.
     */
    FailedPrecondition = "failed_precondition",

    /**
     * Aborted indicates the operation was aborted, typically due to a
     * concurrency issue like sequencer check failures, transaction aborts,
     * etc.
     *
     * See litmus test above for deciding between FailedPrecondition,
     * Aborted, and Unavailable.
     */
    Aborted = "aborted",

    /**
     * OutOfRange means operation was attempted past the valid range.
     * E.g., seeking or reading past end of file.
     *
     * Unlike InvalidArgument, this error indicates a problem that may
     * be fixed if the system state changes. For example, a 32-bit file
     * system will generate InvalidArgument if asked to read at an
     * offset that is not in the range [0,2^32-1], but it will generate
     * OutOfRange if asked to read from an offset past the current
     * file size.
     *
     * There is a fair bit of overlap between FailedPrecondition and
     * OutOfRange. We recommend using OutOfRange (the more specific
     * error) when it applies so that callers who are iterating through
     * a space can easily look for an OutOfRange error to detect when
     * they are done.
     *
     * This error code will not be generated by the gRPC framework.
     */
    OutOfRange = "out_of_range",

    /**
     * Unimplemented indicates operation is not implemented or not
     * supported/enabled in this service.
     *
     * This error code will be generated by the gRPC framework. Most
     * commonly, you will see this error code when a method implementation
     * is missing on the server. It can also be generated for unknown
     * compression algorithms or a disagreement as to whether an RPC should
     * be streaming.
     */
    Unimplemented = "unimplemented",

    /**
     * Internal errors. Means some invariants expected by underlying
     * system has been broken. If you see one of these errors,
     * something is very broken.
     *
     * This error code will be generated by the gRPC framework in several
     * internal error conditions.
     */
    Internal = "internal",

    /**
     * Unavailable indicates the service is currently unavailable.
     * This is a most likely a transient condition and may be corrected
     * by retrying with a backoff. Note that it is not always safe to retry
     * non-idempotent operations.
     *
     * See litmus test above for deciding between FailedPrecondition,
     * Aborted, and Unavailable.
     *
     * This error code will be generated by the gRPC framework during
     * abrupt shutdown of a server process or network connection.
     */
    Unavailable = "unavailable",

    /**
     * DataLoss indicates unrecoverable data loss or corruption.
     *
     * This error code will not be generated by the gRPC framework.
     */
    DataLoss = "data_loss",

    /**
     * Unauthenticated indicates the request does not have valid
     * authentication credentials for the operation.
     *
     * The gRPC framework will generate this error code when the
     * authentication metadata is invalid or a Credentials callback fails,
     * but also expect authentication middleware to generate it.
     */
    Unauthenticated = "unauthenticated",
}
